export const mockPersonnelData = [
  {
    Id: 1,
    regtNumber: "NDRF001",
    name: "Rajesh Kumar",
    rank: "ASI",
    coy: "A",
    doj: "2020-01-15",
    bfrcStatus: "Completed",
    modulesPending: [],
    completedAt: ["NDRF Academy"],
    yearOfCompletion: 2020,
    grading: "A"
  },
  {
    Id: 2,
    regtNumber: "NDRF002",
    name: "Priya Sharma",
    rank: "HC",
    coy: "B",
    doj: "2021-03-10",
    bfrcStatus: "Not Completed",
    modulesPending: ["MFR", "CSSR"],
    completedAt: [],
    yearOfCompletion: null,
    grading: ""
  },
  {
    Id: 3,
    regtNumber: "NDRF003",
    name: "Amit Singh",
    rank: "SI",
    coy: "C",
    doj: "2019-07-20",
    bfrcStatus: "Completed",
    modulesPending: [],
    completedAt: ["Bn HQ"],
    yearOfCompletion: 2019,
    grading: "B+"
  },
  {
    Id: 4,
    regtNumber: "NDRF004",
    name: "Sunita Devi",
    rank: "CT",
    coy: "D",
    doj: "2022-05-12",
    bfrcStatus: "Not Completed",
    modulesPending: ["ADRC", "CBRN", "DBM"],
    completedAt: [],
    yearOfCompletion: null,
    grading: ""
  },
  {
    Id: 5,
    regtNumber: "NDRF005",
    name: "Vikram Yadav",
    rank: "Insp",
    coy: "E",
    doj: "2018-11-05",
    bfrcStatus: "Completed",
    modulesPending: [],
    completedAt: ["NDRF Academy", "NIMS"],
    yearOfCompletion: 2018,
    grading: "A+"
  },
  {
    Id: 6,
    regtNumber: "NDRF006",
    name: "Meera Gupta",
    rank: "HC",
    coy: "F",
    doj: "2021-09-18",
    bfrcStatus: "Completed",
    modulesPending: [],
    completedAt: ["NDRF Academy"],
    yearOfCompletion: 2021,
    grading: "A"
  },
  {
    Id: 7,
    regtNumber: "NDRF007",
    name: "Ravi Patel",
    rank: "ASI",
    coy: "HQ",
    doj: "2020-08-25",
    bfrcStatus: "Not Completed",
    modulesPending: ["MFR"],
    completedAt: [],
    yearOfCompletion: null,
    grading: ""
  },
  {
    Id: 8,
    regtNumber: "NDRF008",
    name: "Kavita Joshi",
    rank: "CT",
    coy: "A",
    doj: "2022-01-30",
    bfrcStatus: "Completed",
    modulesPending: [],
    completedAt: ["Bn HQ"],
    yearOfCompletion: 2022,
    grading: "B"
  },
  {
    Id: 9,
    regtNumber: "NDRF009",
    name: "Deepak Verma",
    rank: "SI",
    coy: "B",
    doj: "2019-04-14",
    bfrcStatus: "Completed",
    modulesPending: [],
    completedAt: ["NDRF Academy"],
    yearOfCompletion: 2019,
    grading: "A+"
  },
  {
    Id: 10,
    regtNumber: "NDRF010",
    name: "Anjali Mishra",
    rank: "HC",
    coy: "C",
    doj: "2021-12-08",
    bfrcStatus: "Not Completed",
    modulesPending: ["CSSR", "ADRC"],
    completedAt: [],
    yearOfCompletion: null,
    grading: ""
  }
]